version: '3.7'
services:
  livekit-server:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"   # API & WebSocket port
      - "5349:5349"   # TURN port
    environment:
      # Use LIVEKIT_API_KEY and LIVEKIT_API_SECRET from .env
      LIVEKIT_KEYS: "${LIVEKIT_API_KEY}:${LIVEKIT_API_SECRET}"
    restart: unless-stopped
    # Optional: mount volumes for data persistence
    # volumes:
    #   - livekit-data:/data

#volumes:
#  livekit-data:
#    name: livekit-data