name: Cleanup Neon Database Branches

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday
  workflow_dispatch:  # Allow manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Neon CLI
        run: npm install -g neonctl

      - name: Authenticate with Neon
        run: echo "${{ secrets.NEON_API_KEY }}" | neon auth --api-key

      - name: Run cleanup script
        run: ./neon_branch_cleanup.sh ${{ secrets.NEON_PROJECT_ID }} 30
